#!/bin/bash
# mkiso.sh — assemble a bootable HadalOS ISO with Limine.
#
# Takes the squashfs catalyst produced and builds a hybrid BIOS+UEFI image.
# Catalyst is not asked to do this: its ISO support is built around isolinux
# and GRUB, whereas Limine needs `limine bios-install` run against the finished
# image plus its own limine.conf. See catalyst/livecd-stage2.spec for the full
# reasoning.
#
#   scripts/mkiso.sh --squashfs <path> --output <path> [--kernel <vmlinuz>]
#                    [--initrd <initrd>] [--limine <dir>] [--volid <label>]
#
# The kernel and initrd default to being extracted from the squashfs, which is
# what you want: the ISO then boots the same kernel an installed system runs,
# rather than a separately built one that can drift from it.

set -euo pipefail

SQUASHFS=""
OUTPUT=""
KERNEL=""
INITRD=""
LIMINE_DIR=""
VOLID="HADALOS"
KEEP_TREE=0

log() { printf '\033[1;36m:: %s\033[0m\n' "$*"; }
die() { printf '\033[1;31mxx %s\033[0m\n' "$*" >&2; exit 1; }

while (( $# )); do
    case "$1" in
        --squashfs) SQUASHFS="${2:?}"; shift 2 ;;
        --output)   OUTPUT="${2:?}";   shift 2 ;;
        --kernel)   KERNEL="${2:?}";   shift 2 ;;
        --initrd)   INITRD="${2:?}";   shift 2 ;;
        --limine)   LIMINE_DIR="${2:?}"; shift 2 ;;
        --volid)    VOLID="${2:?}";    shift 2 ;;
        --keep-tree) KEEP_TREE=1; shift ;;
        -h|--help)  sed -n '2,16p' "$0" | sed 's/^# \?//'; exit 0 ;;
        *)          die "unknown argument: $1" ;;
    esac
done

[[ -n $SQUASHFS ]] || die "--squashfs is required"
[[ -n $OUTPUT   ]] || die "--output is required"
[[ -r $SQUASHFS ]] || die "cannot read $SQUASHFS"

for tool in xorriso; do
    command -v "$tool" >/dev/null || die "missing $tool (dev-libs/libisoburn)"
done

# Limine ships its boot artefacts in a share directory; the binary that stamps
# the BIOS boot record is separate from them.
if [[ -z $LIMINE_DIR ]]; then
    for candidate in /usr/share/limine /usr/local/share/limine; do
        [[ -d $candidate ]] && { LIMINE_DIR="$candidate"; break; }
    done
fi
[[ -n $LIMINE_DIR && -d $LIMINE_DIR ]] || die "Limine data not found; pass --limine (sys-boot/limine)"

for f in limine-bios.sys limine-bios-cd.bin limine-uefi-cd.bin BOOTX64.EFI; do
    [[ -r $LIMINE_DIR/$f ]] || die "missing $LIMINE_DIR/$f -- is sys-boot/limine built with USE=\"bios efi64\"?"
done

TREE="$(mktemp -d)"
cleanup() { (( KEEP_TREE )) || rm -rf "$TREE"; }
trap cleanup EXIT

log "staging ISO tree at $TREE"
mkdir -p "$TREE/boot/limine" "$TREE/EFI/BOOT" "$TREE/LiveOS"

# ── kernel and initrd ─────────────────────────────────────────────────
# Pulled out of the squashfs by default so the ISO boots exactly the kernel
# the installed system will run.
if [[ -z $KERNEL || -z $INITRD ]]; then
    command -v unsquashfs >/dev/null || die "need unsquashfs to extract the kernel (sys-fs/squashfs-tools)"
    log "extracting kernel and initrd from the squashfs"
    unsquashfs -q -f -d "$TREE/.extract" "$SQUASHFS" 'boot/*' >/dev/null \
        || die "could not extract /boot from $SQUASHFS"

    [[ -n $KERNEL ]] || KERNEL="$(find "$TREE/.extract/boot" -name 'vmlinuz*' -type f | sort -V | tail -1)"
    [[ -n $INITRD ]] || INITRD="$(find "$TREE/.extract/boot" -name 'initr*' -type f | sort -V | tail -1)"
fi

[[ -r ${KERNEL:-} ]] || die "no kernel found; pass --kernel"
[[ -r ${INITRD:-} ]] || die "no initrd found; pass --initrd"

log "kernel: $(basename "$KERNEL")"
log "initrd: $(basename "$INITRD")"
install -m 0644 "$KERNEL" "$TREE/boot/vmlinuz"
install -m 0644 "$INITRD" "$TREE/boot/initrd"
rm -rf "$TREE/.extract"

install -m 0644 "$SQUASHFS" "$TREE/LiveOS/squashfs.img"

for f in limine-bios.sys limine-bios-cd.bin limine-uefi-cd.bin; do
    install -m 0644 "$LIMINE_DIR/$f" "$TREE/boot/limine/$f"
done
install -m 0644 "$LIMINE_DIR/BOOTX64.EFI" "$TREE/EFI/BOOT/BOOTX64.EFI"

# ── boot menu ─────────────────────────────────────────────────────────
# root=live:CDLABEL= is what dracut's dmsquash-live module looks for, which is
# why the volume id below and the one here must not drift apart.
cat > "$TREE/boot/limine.conf" <<EOF
# Generated by mkiso.sh. The installed system's menu is generated instead by
# hadalos-limine-update, from what is actually on disk.
timeout: 10
default_entry: 1

/HadalOS (live)
    protocol: linux
    path: boot():/boot/vmlinuz
    cmdline: root=live:CDLABEL=$VOLID rd.live.image quiet
    module_path: boot():/boot/initrd

/HadalOS (live, verbose)
    protocol: linux
    path: boot():/boot/vmlinuz
    cmdline: root=live:CDLABEL=$VOLID rd.live.image
    module_path: boot():/boot/initrd

/HadalOS (live, no modeset)
    protocol: linux
    path: boot():/boot/vmlinuz
    cmdline: root=live:CDLABEL=$VOLID rd.live.image nomodeset
    module_path: boot():/boot/initrd
EOF

# ── build ─────────────────────────────────────────────────────────────
log "building $OUTPUT"
mkdir -p "$(dirname "$OUTPUT")"

# Limine's documented hybrid invocation. -no-emul-boot with boot-load-size 4
# is the El Torito no-emulation form; the EFI half rides along as a second
# boot record so one image boots on both firmware types.
xorriso -as mkisofs \
    -R -r -J \
    -V "$VOLID" \
    -b boot/limine/limine-bios-cd.bin \
    -no-emul-boot -boot-load-size 4 -boot-info-table \
    --efi-boot boot/limine/limine-uefi-cd.bin \
    -efi-boot-part --efi-boot-image \
    --protective-msdos-label \
    "$TREE" -o "$OUTPUT"

# Stamps the BIOS boot record into the image. Without it the ISO boots on UEFI
# and hangs on BIOS, which is a confusing way to find out.
if command -v limine >/dev/null; then
    log "installing the Limine BIOS stage"
    limine bios-install "$OUTPUT"
else
    printf '\033[1;33m!! limine binary not found; skipped bios-install.\n'
    printf '   The image will boot under UEFI only.\033[0m\n'
fi

log "done: $OUTPUT ($(du -h "$OUTPUT" | cut -f1))"
(( KEEP_TREE )) && log "tree kept at $TREE"
exit 0
